### ISSUE TITLE
avalonia 11.0.4

### ISSUE THREAD

**Issue by Mr4g** [OutSystems/CefGlue#106]
When using this on avalonia 11.0.4 I have this problem :
System.IO.FileNotFoundException: 'Could not load file or assembly "Avalonia.Visuals, Version=0.10.17.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b". The specified file could not be found.'

**Comment by joaompneves** [comment]
https://github.com/OutSystems/CefGlue/issues/99
