### ISSUE TITLE
CefGlue.Common nuget package: NLog dependency 

### ISSUE THREAD

**Issue by elgonzo** [OutSystems/CefGlue#108]
The CefGlue.Common 106.5249.21 nuget package has a dependency on NLog.

But CefGlue.Common does not seem to be using NLog. As far as i can tell by inspecting the source and build files, any NLog-related code is gated by an `HAS_NLOG` symbol that however appears to be undefined. Which is also supported by my observation that Visual Studio's IntelliSense does not offer the `Xilium.CefGlue.Common.Helpers.Logger.ILogInitializer` and `Xilium.CefGlue.Common.Helpers.Logger.NLogLogger` types in a project using the CefGlue.Common 106.5249.21 nuget package.

This and the comment in:

https://github.com/OutSystems/CefGlue/blob/5a52f852c521711278d71132af8b334c3f29a246/CefGlue.Common/Helpers/Logger/Logger.cs#L1-L3

strongly suggests that the NLog dependency of the CefGlue.Common nuget package is in error.

**Comment by joaompneves** [comment]
You're right. This package dependency should also be conditional, or removed all the way. Probably consumers should be able to inject their own loggers.
Feel free to open a PR that removes the NLog traces

**Comment by elgonzo** [comment]
@joaompneves 

What about the conditional code that is gated by the `HAS_NLOG` symbol? Should it be removed with the NLog package dependency, or should it stay in the codebase?

**Comment by joaompneves** [comment]
you can make it conditional also.. we should review the approach later

**Comment by joaompneves** [comment]
Solved
