### ISSUE TITLE
This browser or app may not be secure

### ISSUE THREAD

**Issue by vmachacek** [OutSystems/CefGlue#113]
When I run the demo and go to google's calendar and try to log in it won't work. 

Any idea how to trick google into trusting this browser?

## Couldn't sign you in 

This browser or app may not be secure. Learn more
Try using a different browser. If you're already using a
supported browser, you can try again to sign in.

![image](https://github.com/OutSystems/CefGlue/assets/2987885/51ff214d-4b22-41d0-9b7c-134081a607f9)

**Comment by joaompneves** [comment]
Hey:

Check this thread to understand why:
https://magpcss.org/ceforum/viewtopic.php?t=16764

**Comment by vmachacek** [comment]
@joaompneves thank you, that is very helpful
