### ISSUE TITLE
Avalonia adorner

### ISSUE THREAD

**Issue by Maliverka** [OutSystems/CefGlue#116]
Hello, the browser part of my application is blocking the avalonia adorner. How can I display the avalonia adorner on top of the browser?
Avalonia version: 10.22

**Comment by joaompneves** [comment]
Hi,
You need to use the offscreen rendering capabilities, setting [this property](https://github.com/OutSystems/CefGlue/blob/main/CefGlue.Demo.Avalonia/Program.cs#L21)

Beware that this brings some performance and behavior issues, and its recommend to stay off.
