### ISSUE TITLE
Avalonia 11.0.5 Compatibility with CefGlue?

### ISSUE THREAD

**Issue by aadi1295** [OutSystems/CefGlue#118]
Is this compatible with Avalonia 11.0.5? I am unable to run this on 11.0.5. Please advice.

**Comment by liuxyxh** [comment]
I have also encountered this issue, please fix it as soon as possible. Thank you very much

**Comment by joaompneves** [comment]
Whats the issue? Have you tried this https://github.com/OutSystems/CefGlue/pull/82?

**Comment by JerryJian** [comment]
Also try to install the package with [-avalonia11](https://www.nuget.org/packages/CefGlue.Avalonia/117.5938.2-avalonia11) suffix.
