### ISSUE TITLE
Avalonia 11.0.6 in macos input

### ISSUE THREAD

**Issue by klousCan** [OutSystems/CefGlue#128]
Unable to enter text on macos x64 after setting WindowlessRenderingEnabled to true. Switching to the Chinese input method at the same time will cause the program to crash.
CefGlue.Avalonia version:117.5938.2-avalonia11
![image](https://github.com/OutSystems/CefGlue/assets/9686646/023de048-a218-4f8a-ba5e-7bc9800c7d42)

**Comment by klousCan** [comment]
After upgrading cef.redist.osx64, the Chinese crash problem was solved, but the content could not be entered in the text box

**Comment by joaompneves** [comment]
does it happen with WindowlessRenderingEnabled = false?

**Comment by klousCan** [comment]
@joaompneves It has no problem with WindowlessRenderingEnabled = false

**Comment by klousCan** [comment]
I also have issues upgrading it to the latest version
CefGlue.Avalonia version 120

**Comment by joaompneves** [comment]
WindowlessRenderingEnabled = false is the recommended value.

**Comment by klousCan** [comment]
@tkefauver  I think it's avalonia's problem and I've submitted issues.I didn't encounter this problem on Windows because I used cefnet
