### ISSUE TITLE
Publishing new version of cef.redist.linux.x64?

### ISSUE THREAD

**Issue by mtniehaus** [OutSystems/CefGlue#129]
I've been experimenting with the Linux PR (a good learning process on the challenges of .NET Core) and merged in the latest changes from main to my local branch, but I found that there isn't a NuGet package of cef.redist.linux.x64 for version 120.2.4.  Any chance you could publish one to NuGet?

I also noticed that there was a missing file (libvulkan.so.1) that is included in the cef binary releases but not in the NuGet package -- if that file is not present, the cefsample app won't run on the same Linux system where I'm trying to use the CefGlue.Demo.Avalonia app (unsuccessfully so far -- made some progress, but still not enough to actually get the app to fully load).

**Comment by joaompneves** [comment]
Hi,

You may create that package from here:
https://github.com/joaompneves/cef.redist.linux

There has been several attempts from the community to make this run on Linux but no one has made it to the end.

**Comment by mtniehaus** [comment]
Cool, I've got that, using a local package for now.  I'm still hacking away at getting it to run on Linux.

**Comment by joaompneves** [comment]
Linux support, now available: [120.6099.204](https://www.nuget.org/packages/CefGlue.Avalonia/120.6099.204)
