### ISSUE TITLE
Headless support (for automated tests)?

### ISSUE THREAD

**Issue by MihaMarkic** [OutSystems/CefGlue#130]
Hi,

Looking for a headless cross platform browser for running automated tests - is there support for it in here?

TIA

**Comment by MihaMarkic** [comment]
Looks like [this article](https://www.joelverhagen.com/blog/2013/12/headless-chromium-in-c-with-cefglue/) is on right path, although it needs a bit of a refresh.

**Comment by joaompneves** [comment]
Hi,
This project provides a visual component (webview) for Avalonia. Doesn't aim to provide headless capabilities.

**Comment by MihaMarkic** [comment]
@joaompneves While that's true, it still indirectly provides headless functionality, it seems.

**Comment by MihaMarkic** [comment]
@joaompneves Could this be something you might support eventually? Otherwise close the issue I guess.

**Comment by joaompneves** [comment]
Hi,
Not really. You should look at the original CefGlue [repo](https://gitlab.com/xiliumhq/chromiumembedded/cefglue) rather than this one. As I said, this one is about providing a visual cross platform component, not and headless one.
