### ISSUE TITLE
Chrome runtime support

### ISSUE THREAD

**Issue by EugeneSunrise** [OutSystems/CefGlue#145]
Im using custom cefsharp to create several native chrome ui windows and recently there was a question of switching to a cross-platform solution, avalonia + cefglue with ChromeRuntime = true - always crashes on cef initialization without any log, also tried to update to 126v - nothing changed. Is there any plans to update CEF to the latest version(chrome bootstrap etc)? Thanks

**Comment by joaompneves** [comment]
I recommend that you check the [CEF forums](https://www.magpcss.org/ceforum/) to understand how to properly enable or what needs to be done to enable chrome runtime.
Regarding cef update, we do it from time to time, although you can expect some delay.
