### ISSUE TITLE
Crash in CefGlue.Demo.WPF

### ISSUE THREAD

**Issue by ArnoKrohne** [OutSystems/CefGlue#151]
Running a debug build of CefGlue.Demo.WPF from a CEFGlue clone crashes with an access violation in libcef.dll in the CefUIThread. 

It is using .NET8 on Windows 10

This may have something to do with something I observed in another project: the Xilium.CefGlue.BrowserProcess is not started.

However, in that case Xilium.CefGlue.BrowserProcess was not even in the generated output. When I copied Xilium.CefGlue.BrowserProcess manually it had a result similar to the one in CefGlue.Demo.WPF.

**Comment by joaompneves** [comment]
Hi, does [this](https://github.com/OutSystems/CefGlue/pull/150) fix the issue?

**Comment by ArnoKrohne** [comment]
Unfortunately is doesn't. The only difference is that it crashes in another location in the CEFUIThread. But I think the exact location is is not always the same anyway.  Same other symptom: Xilium.CefGlue.BrowserProcess is not running. I have also tried the WebView project with avalonia. That example does run properly and 4 Xilium.CefGlue.BrowserProcess are started.

**Comment by joaompneves** [comment]
Check the last version: 120.6099.205. We removed the support for dotnet 6 which was causing these build issues.
