### ISSUE TITLE
CefGlue.Avalonia Broken

### ISSUE THREAD

**Issue by Sayayaya** [OutSystems/CefGlue#157]
I updated CefGlue.Avalonia to version 120.6099.204

Now when ```browser = new AvaloniaCefBrowser();``` is called, an exception is thrown.

`System.IO.FileNotFoundException: 'Unable to find SubProcess. Probed locations: `

It then lists locations it has looked in. I observe it mentions CefGlueBrowserProcess folder, which I observe to be an empty folder. Somethings not right in this build or you are missing instructions on how to get this build to work.

Cheers,

**Comment by SteamMatthew** [comment]
I can agree with this issue, I see the same problem. Not currently using WPF in my project, I did a related fix for https://github.com/OutSystems/CefGlue/issues/144.

I thought on one of my machines I had it building correctly after messing with the build targets enough times. Maybe I was hallucinating it working after enough times.

Missing `Xilium.CefGlue.BrowserProcess.exe` and related files in my build directory. 

Went ahead and copied my working build output from my VM for my project manually into my build in the meantime.

**Comment by RusselRillema** [comment]
Getting the same error. 

Avalonia 11.1.3
WebViewControl-Avalonia 3.120.4
    WebViewControl-Avalonia 120.6099.204

Anyone have a workaround?

**Comment by joaompneves** [comment]
Check the last version: 120.6099.205. We removed the support for dotnet 6 which was causing these build issues.

**Comment by SteamMatthew** [comment]
Thank for this update. 

Now using the  `120.6099.205` version just posted a few mins ago. 

I deleted the browser folder and got successfully re-added. Thank you. :)
