### ISSUE TITLE
How to return data from the webpage.

### ISSUE THREAD

**Issue by NorMoll** [OutSystems/CefGlue#165]
In Avalonia how would I use ExecuteJavaScript or EvaluateJavaScript to return a list of elements on the page?

**Comment by joaompneves** [comment]
Check the sample:
https://github.com/OutSystems/CefGlue/blob/main/CefGlue.Demo.Avalonia/BrowserView.axaml.cs#L85

**Comment by NorMoll** [comment]
Hi there, thanks for the prompt response, I’ve managed to solve the issue returning an object[]
