### ISSUE TITLE
Scrollbar match Avalonia?

### ISSUE THREAD

**Issue by Sayayaya** [OutSystems/CefGlue#167]
I wonder is it possible to have the Scrollbar match the scrollbars that are rendered in Avalonia?

It would be nice to have the scrollbar match for app consistency.

**Comment by joaompneves** [comment]
CefGlue is a browser engine (=Chromium) that limits to render the pages. To change the scrollbars inside CefGlue you need to change the css of the pages that you render. There's no (easy) way to change that by default AFAIK.
