### ISSUE TITLE
Process never closes

### ISSUE THREAD

**Issue by MangoDevx** [OutSystems/CefGlue#169]
After running my Avalonia application with OutSystems/WebView I tried to delete my published build folder. I am unable to delete it because "Xilium.CefGlue.BrowserProcess.exe" is still open. It seems the process does not clean up or end itself.

**Comment by joaompneves** [comment]
Did you tried the sample:
https://github.com/OutSystems/CefGlue/tree/main/CefGlue.Demo.Avalonia

Does it happen also, or just in your app?

**Comment by MangoDevx** [comment]
Sorry, I am unable to repro this week.
