### ISSUE TITLE
Avalonia Browser View disable resizing edge

### ISSUE THREAD

**Issue by nova-zyura** [OutSystems/CefGlue#22]
Cannot resize browserview in full extended view

**Comment by joaompneves** [comment]
Can you detail a bit more the problem and how to reproduce it?

**Comment by nova-zyura** [comment]
![image](https://user-images.githubusercontent.com/80867835/135712910-82dda299-8872-423c-816d-8df7306af39d.png)
this is when the margin is set, i can resize window, but without margin this cannot be done

**Comment by joaompneves** [comment]
You need to add a margin. There's no way that I know to overcome that.
