### ISSUE TITLE
Is there documentation of what the features are and the API?

### ISSUE THREAD

**Issue by abukres** [OutSystems/CefGlue#44]
Is there documentation of what the features are and the API? The documentation seems to be just a couple of samples which means someone has to know Avalonia or WFP and dig in the code. Does the code use every feature and API? 
I would have preferred to see real documentation.

**Comment by joaompneves** [comment]
You have the sample and several of the public APIs have a small description of their purpose ([example](https://github.com/OutSystems/CefGlue/blob/4472/CefGlue.Common/BaseCefBrowser.cs#L106)).
