### ISSUE TITLE
Difference between this CefGlue and Dmitry Azaraev CefGlue

### ISSUE THREAD

**Issue by Patowhiz** [OutSystems/CefGlue#48]
Is there a difference between this CefGlue and [Dmitry Azaraev](https://gitlab.com/xiliumhq/chromiumembedded/cefglue) CefGlue. Or is it an extension of his?

**Comment by joaompneves** [comment]
Hi,

This started as a fork from that repo but evolved with some of the following features:

- Avalonia control (CefGlue can now run on Windows and OSX with this implementation)
- Ability to execute and evaluate javascript (can handle multiple calls at the same time)
- Javascript evaluation converts the response to .net objects
- Ability to setup several Cef handlers (eg: Download Handler, Drag Handler, KeyBoardHandler, ...)
- Javascript native objects registration (call .net methods from JS and get values)
- Open developer tools
- More browser events
- Browser process is now an independant app - smaller footprint and does not have impacts on the host app (eg: command-line processing)
- .NET 5 compliant

**Comment by Patowhiz** [comment]
@joaompneves thanks for the quick response. 
May ask which Chromium build it's currently using?

**Comment by joaompneves** [comment]
Currently 91. Our versioning scheme reflects that (Major.Minor)
It might be upgraded anytime.

**Comment by Patowhiz** [comment]
@joaompneves thanks for all your feedback. Highly appreciated.
