### ISSUE TITLE
Demo.Avalonia  doesn't work with Avalonia >= 0.10.14

### ISSUE THREAD

**Issue by sakya** [OutSystems/CefGlue#50]
Using Avalonia version >= 0.10.14 the browser view is rendered outside the main window.
![image](https://user-images.githubusercontent.com/289552/176463858-f798aed6-3489-4036-abae-b7be4f448309.png)

**Comment by joaompneves** [comment]
@sakya can you check the pull request to see that it fixes the issue?

**Comment by sakya** [comment]
Yes, now it works fine, many thanks!
