### ISSUE TITLE
Are there any plans to upgrade the Chromium build 91.0.4472.77 ?

### ISSUE THREAD

**Issue by santiago-ribero** [OutSystems/CefGlue#53]
Hi.
As far as I can see, the current implementation uses Chromium build 91.0.4472.77 .
Our product uses ChromiumFX (CEF 3.3440 / Chromium 68.0.3440) and due to some vulnerabilities in that Chromium version, we have to upgrade to 98.0.4758 or higher.

Are there any plans to upgrade, in CefGlue, the Chromium build from 91.0.4472.77 to 98.0.4758 or higher?

Thank you. Kind regards.

**Comment by joaompneves** [comment]
Hi,
Can't put a date on that.
Opened a PR, but there are several breaking changes that are preventing the build to succeed. I don't have time right now to work on it.

**Comment by joaompneves** [comment]
We're almost finishing the upgrade to chromium 106 [here](https://github.com/OutSystems/CefGlue/pull/56)
