### ISSUE TITLE
Cannot pass Command Line Arguments to CEF Initialize

### ISSUE THREAD

**Issue by Niebvelungen** [OutSystems/CefGlue#59]
I need to give an command line argument to CEF, but it is currently not possible to do that in the Program initialize.

CefRuntimeLoader.cs: 66
` CefRuntime.Initialize(new CefMainArgs(new string[0]), settings, new BrowserCefApp(customSchemes, flags, browserProcessHandler), IntPtr.Zero);` 
Here an empty array gets passed, where command line arguments are normally passed through.

**Comment by joaompneves** [comment]
Hi,

`CefRuntimeLoader.Initialize` has a param named `flags` that can be used for that purpose

**Comment by Niebvelungen** [comment]
OK for some reason the "disable-web-security" argument does not work.
On the CEF Forum i found a Post that this argument has to be passed via command args.
I need to disable CORS for the Browser for a local site i am using.
Not sure this is the right place to ask but do you have an idea why the flag is not working?

Reference implementation:

Programm.cs
`
var cefFlags = new Dictionary<string, string>();
            cefFlags.Add("disable-pinch", "true");
            cefFlags.Add("disable-web-security", "true");


            BuildAvaloniaApp()
            .UsePlatformDetect()
            .With(new Win32PlatformOptions
            {
                UseWindowsUIComposition = false
            })
                      .AfterSetup(_ => CefRuntimeLoader.Initialize(new CefSettings()
                      {
                          
#if WINDOWLESS
                          WindowlessRenderingEnabled = true
#else
                          WindowlessRenderingEnabled = false
#endif
                      }, cefFlags.ToArray()))
            .StartWithClassicDesktopLifetime(args);
`

**Comment by joaompneves** [comment]
according to the chromium source code, you also need to specify user data dir
https://source.chromium.org/chromium/chromium/src/+/main:content/public/common/content_switches.cc;l=281?q=kDisableWebSecurity&ss=chromium
