### ISSUE TITLE
App Crash on Windows with Avalonia 11 preview6 version

### ISSUE THREAD

**Issue by sandreas** [OutSystems/CefGlue#83]
Hello @joaompneves,

after integrating `CefGlue` into an Avalonia 11 Preview6 xplat app, on macOS everything works like expected. Unfortunately on the main target platform Windows 10 the App crashes without saying a word  (in the debugger as well as in release mode) - it's just gone.

I'm pretty sure that this has to do with `CefGlue`, because if I comment out ONLY the`BrowserView` I created with `CefGlue`, everything works like expected. 

Since the App I'm working on is not open source, I'll try to provide a minimal example to reproduce the bug in the next days. Until then, here is the `BrowserView` Control code.

May be important, that two of the controls may be loading at the same time...

Are you able to test on Windows?

```xaml
<!-- BrowserView.axaml -->
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:browser="clr-namespace:MyApp.Controls.Browser"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="MyApp.Controls.Browser.BrowserView"
             x:DataType="browser:BrowserView"
             >
    <Decorator x:Name="BrowserWrapper" IsVisible="{Binding IsBrowserVisible}"/>
</UserControl>
```

```c#
// BrowserView.axaml.cs

using System;
using System.Windows.Input;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using Xilium.CefGlue.Avalonia;
using Xilium.CefGlue.Common.Events;

namespace MyApp.Controls.Browser;


public partial class BrowserView : UserControl, IDisposable
{
    public static readonly StyledProperty<ICommand?> UrlChangedCommandProperty =
        AvaloniaProperty.Register<BrowserView, ICommand?>(nameof(UrlChangedCommand), enableDataValidation: true);


    public ICommand? UrlChangedCommand
    {
        get => GetValue(UrlChangedCommandProperty);
        set => SetValue(UrlChangedCommandProperty, value);
    }


    public static Func<AvaloniaCefBrowser>? CreateBrowser = null;

    private AvaloniaCefBrowser? _browser;

    public bool IsBrowserVisible => !_isLoading && string.IsNullOrEmpty(Message);

    public string Message { get; set; } = "";

    private bool _isLoading;

    public static readonly StyledProperty<string>
        UrlProperty = // todo remove static keyword to allow multiple instances?
            AvaloniaProperty.Register<BrowserView, string>(
                nameof(Url),
                defaultValue: "about:blank");

    public string Url
    {
        get => GetValue(UrlProperty);
        set => SetValue(UrlProperty, value);
    }

    public BrowserView()
    {
        InitializeComponent();
    }



    protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
    {
        base.OnPropertyChanged(change);
        if (change.Property == UrlProperty && _browser != null /* && _browser.Address != Url*/)
        {
            if (_browser.Address == Url)
            {
                _browser.Reload();
            }
            else
            {
                _browser.Address = Url;
            }
        }
    }

    private void InitializeComponent()
    {
        AvaloniaXamlLoader.Load(this);
        var browserWrapper = this.FindControl<Decorator>("BrowserWrapper");

        if (browserWrapper == null)
        {
            return;
        }

        Console.WriteLine("Initialize BrowserView: " + Url);

        _browser = new AvaloniaCefBrowser();
        _browser.Address = Url;
        _browser.LoadStart += OnBrowserLoadStart;
        _browser.LoadEnd += OnBrowserLoadEnd;
        
        _browser.LoadError += OnBrowserLoadError;
        _browser.TitleChanged += OnTitleChanged;
        browserWrapper.Child = _browser;
    }

    private void OnBrowserLoadStart(object sender, LoadStartEventArgs e)
    {
        if (e.Frame.Browser.IsPopup || !e.Frame.IsMain)
        {
            return;
        }

        _isLoading = true;
        Message = "";
    }

    private void OnBrowserLoadError(object sender, LoadErrorEventArgs e)
    {
        _isLoading = false;
        Message = $"Could not load {e.FailedUrl}: {e.ErrorText} ({e.ErrorCode})";
    }

    private void OnBrowserLoadEnd(object sender, LoadEndEventArgs e)
    {
        _isLoading = false;
        if (_browser != null && Url != _browser.Address)
        {
            if (UrlChangedCommand?.CanExecute(_browser.Address) ?? false)
            {
                UrlChangedCommand?.Execute(_browser.Address);
            }
        }
    }

    private void OnTitleChanged(object sender, string title)
    {
        _isLoading = false;
    }

    public void Dispose()
    {
        _browser?.Dispose();
    }
}
```

**Comment by joaompneves** [comment]
Hi,

I don't have a Windows machine :(
Have you tried [this](https://github.com/OutSystems/CefGlue/tree/avalonia11/CefGlue.Demo.Avalonia) sample on windows?

**Comment by sandreas** [comment]
@joaompneves Thank you for the quick response.

> Have you tried [this](https://github.com/OutSystems/CefGlue/tree/avalonia11/CefGlue.Demo.Avalonia) sample on windows?

No, not yet. I'll try it, and if it does not work, I'll provide an example and try to set up a Windows VM for VirtualBox that you can download to test... would this be ok? 
Or maybe you don't wanna get into windows at all (I would understand that)?

**Comment by Jun-Murakami** [comment]
Hi, it works fine in my environment.
(The NuGet Package must be selected manually.)
---
Windows 10 Pro 21H2
CefGlue 106.5249.7-avalonia11
Avalonia v11 preview6

![sss](https://user-images.githubusercontent.com/126404131/233769548-64053b58-593b-4166-ab4e-36b70a45c587.png)

**Comment by sandreas** [comment]
@Jun-Murakami Thanks for the feedback... mmh something may be wrong in my implementation. I'll report back, as soon as I tested the "official" example.

**Comment by lvjunlei** [comment]
System.IO.FileNotFoundException:“Could not load file or assembly 'Avalonia.Visuals, Version=0.10.17.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'.

**Comment by joaompneves** [comment]
Asked a colleague to run the sample on Windows and he told me it works fine.

**Comment by sandreas** [comment]
Ok mmh I'll try it asap. I'm sick atm and need to rest a bit

**Comment by xadam1** [comment]
Heya, still getting the error:
`Could not load file or assembly 'Avalonia.Visuals, Version=0.10.17.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b`

Any updates on how to fix those?

**Comment by sandreas** [comment]
@xadam1 
Did you add the  nuget with the -avalonia11 suffix?

```
<PackageReference Include="CefGlue.Avalonia" Version="106.5249.7-avalonia11" />
```

@joaompneves 
I'm closing this due to a lack of time in investigating this. Seems to be only on my system and I don't wanna waste your time. As soon as I have more info, I'll post them here or reopen the issue.
Thanks for your help & patience...
