### ISSUE TITLE
What does it take for Linux? 

### ISSUE THREAD

**Issue by JensNordenbro** [OutSystems/CefGlue#92]

**Comment by joaompneves** [comment]
Hi, there's this [PR](https://github.com/OutSystems/CefGlue/pull/88) opened waiting for feedback to check if its working.

**Comment by maksimwest00** [comment]
@joaompneves hi is linux support planned? your cefglue better efficiency than cefnet but cef net work on linux :(

**Comment by joaompneves** [comment]
No plans, but open to PR that introduces Linux support.

**Comment by joaompneves** [comment]
Now available: [120.6099.204](https://www.nuget.org/packages/CefGlue.Avalonia/120.6099.204)
