### ISSUE TITLE
Avalonia v11 Error

### ISSUE THREAD

**Issue by xadam1** [OutSystems/CefGlue#99]
Hey!

I've been trying to update my Avalonia App to v11 and along with that also the CefGlue package. But when I do so I got an error: 
`Could not load file or assembly 'Avalonia.Visuals, Version=0.10.17.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b`.

But when I try the example from [over here](https://github.com/OutSystems/CefGlue/tree/avalonia11/CefGlue.Demo.Avalonia), it works fine. But this example is built on Avalonia `11.0.0-preview6`. May that be an issue, as v11 is officially released now?

Thanks a lot for the answers!

**Comment by joaompneves** [comment]
I've updated https://github.com/OutSystems/CefGlue/pull/82. Try it out.

**Comment by xadam1** [comment]
Thanks! Quick question, can I somehow try in my project as a NuGet? Because I still see #82 as a `Draft`. So that is not `CefGlue.Avalonia version 106.5249.20`, right?
